### ISSUE TITLE
Use valid JSON.

### ISSUE THREAD

**Issue by adyavanapalli** [ptkinvent/frcsim2020#10]
# Summary

The "JSON" strings exchanged between the various systems in the simulator are not valid JSON strings. Consider implementing a simulator with valid JSON.

## Details

* Valid JSON uses double-quotes `"` instead of single-quotes `'`.
* Valid JSON specifies integers as unpadded integers, so `0000` is invalid. `0` is valid.

**Comment by ptkinvent** [comment]
Solved in 24a95f2608ea0f81f524b903ac64c2ddbf3af309.
